package com.censat.redd_projects_api.model;

public enum ProjectStatus {
    REGISTRADO,
    REGISTRO_COMPLETO,
    NO_REGISTRADO,
    CERTIFICADO,
    EN_VALIDACION,
    EN_VERIFICACION,
    APROBACION_DE_VERIFICACION_SOLICITADA,
    RETIRADO,
    PRE_REGISTRADO,
    CANCELADO,
    SE_SOLICITA_APROBACION_DE_REGISTRO_Y_VERIFICACION,
    EN_DESARROLLO,
    LISTADO
}